"""rospy stub for Windows editing only."""
from typing import Any, Callable


class Rate:
    def __init__(self, hz: float) -> None: ...
    def sleep(self) -> None: ...


class Subscriber:
    def __init__(self, topic: str, msg_type: type, callback: Callable) -> None: ...


class Publisher:
    def __init__(self, topic: str, msg_type: type, queue_size: int = 1) -> None: ...
    def publish(self, msg: Any) -> None: ...


class Time:
    @staticmethod
    def now() -> "Time": ...
    def to_sec(self) -> float: ...
    def __add__(self, other: "Duration") -> "Time": ...
    def __sub__(self, other: "Time") -> "Duration": ...
    def __gt__(self, other: "Time") -> bool: ...
    def __lt__(self, other: "Time") -> bool: ...
    def __ge__(self, other: "Time") -> bool: ...
    def __le__(self, other: "Time") -> bool: ...
    def __eq__(self, other: object) -> bool: ...


class Duration:
    def __init__(self, secs: float) -> None: ...
    def to_sec(self) -> float: ...
    def __add__(self, other: "Duration") -> "Duration": ...
    def __sub__(self, other: "Duration") -> "Duration": ...


class ServiceProxy:
    def __init__(self, name: str, srv_type: type) -> None: ...
    def __call__(self, request: Any) -> Any: ...


def init_node(name: str, anonymous: bool = False) -> None: ...
def get_param(param: str, default: Any = None) -> Any: ...
def sleep(duration: float) -> None: ...
def is_shutdown() -> bool: ...
def loginfo(msg: str) -> None: ...
def loginfo_throttle(period: float, msg: str) -> None: ...
def logwarn(msg: str) -> None: ...
def logerr(msg: str) -> None: ...
def wait_for_service(name: str) -> None: ...
def on_shutdown(callback: Callable) -> None: ...
def spin() -> None: ...
